Обработка заказов
rnikbond/gophermarket pull request #2
Opened 2022-08-05 22:35 UTC by rnikbond

2022-08-09 19:54 UTC, ASPecherkin requested changes
оставил несколько замечаний

2022-08-09 19:54 UTC, ASPecherkin commented on internal/handlers/orders_list.go
> +	if len(orders) < 1 {
тут проще == 0 , потому что отрицательного числа тут быть не может

2022-08-09 19:54 UTC, ASPecherkin commented on internal/repository/repository.go
>  type Authorization interface {
тут скорее дело привычки - обычно разносят интерфейсы к тем бизнес моделям, где оно будет использоваться 
но тут как тебе удобнее

2022-08-09 19:54 UTC, ASPecherkin commented on internal/tasks/scanner.go
> +	ticker := time.NewTicker(1 * time.Second)
лучше вынести это время в конфигурацию 
чтобы проще было в дальнейшем это менять

2022-08-09 19:54 UTC, ASPecherkin commented on internal/tasks/scanner.go
> +	if len(orderAccrual.Status) < 1 {
тоже лучше == 0

2022-08-10 07:35 UTC, rnikbond commented on internal/handlers/orders_list.go
> +	if len(orders) < 1 {
Привычка избегать строгие равенства) Исправил

2022-08-10 07:45 UTC, rnikbond commented on internal/tasks/scanner.go
> +	ticker := time.NewTicker(1 * time.Second)
Исправил

2022-08-10 07:46 UTC, rnikbond commented on internal/tasks/scanner.go
> +	if len(orderAccrual.Status) < 1 {
+

2022-08-10 07:46 UTC, rnikbond commented on internal/tasks/scanner.go
> +	if len(orderAccrual.Status) < 1 {
Поправил

2022-08-10 08:47 UTC, merged